# 데이터베이스 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3000/mydatabase   # 데이터베이스 URL 설정
    username: minyoung                        # 데이터베이스 사용자 이름 설정
    password: minyoung715!                       # 데이터베이스 암호 설정
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect